# Camera- Depth calibration

In [1]:
import mrob
import numpy as np
import open3d as o3d

In [2]:
camera_scene_points = np.load('camera_scene_points.npy')

In [4]:
print(camera_scene_points[0])

[[ 0.55727821 -1.84757072 28.46274022]
 [ 0.5775731  -0.89460131 28.16035403]
 [ 0.59786799  0.05836811 27.85796784]
 [ 0.61816288  1.01133753 27.55558164]
 [ 0.63845778  1.96430694 27.25319545]
 [ 0.65875267  2.91727636 26.95080926]
 [ 0.67904756  3.87024577 26.64842306]
 [ 0.69934245  4.82321519 26.34603687]
 [-0.4416348  -1.84093771 28.4166013 ]
 [-0.42133991 -0.88796829 28.11421511]
 [-0.40104502  0.06500112 27.81182891]
 [-0.38075013  1.01797054 27.50944272]
 [-0.36045523  1.97093995 27.20705652]
 [-0.34016034  2.92390937 26.90467033]
 [-0.31986545  3.87687879 26.60228414]
 [-0.29957056  4.8298482  26.29989794]
 [-1.44054781 -1.8343047  28.37046237]
 [-1.42025292 -0.88133528 28.06807618]
 [-1.39995803  0.07163414 27.76568999]
 [-1.37966314  1.02460355 27.46330379]
 [-1.35936824  1.97757297 27.1609176 ]
 [-1.33907335  2.93054238 26.8585314 ]
 [-1.31877846  3.8835118  26.55614521]
 [-1.29848357  4.83648121 26.25375902]
 [-2.43946082 -1.82767168 28.32432345]
 [-2.41916593 -0.87470227

In [10]:
pi = mrob.registration.estimate_plane(camera_scene_points[0])
print(pi)

[-0.09085514 -0.31210157 -0.94569443 32.19386923]


# load pcd from velodyne

# Segment PC belonging to the plane

# Camera to Lidar calibration